### ISSUE TITLE
Request, Add Order Comments Plugin

### ISSUE THREAD

**Issue by f0rmatme** [Vaalyn/sylius-shop#4]
https://github.com/mangoweb-sylius/SyliusOrderCommentsPlugin

**Comment by Vaalyn** [comment]
I've added the plugin but I needed to fork it to make it really useful since the message column was defined to contain only up to 255 characters which is (in my opinion) not nearly enough to provide useful messages to customers. In the fork I've changed the column type from `string` to `text`. I've also submitted this change as a PR to the original repository of the plugin.

I've also overridden the admin templates to make it look a bit nicer (ignore the german, haven't switched languages for the screenshot):

![image](https://user-images.githubusercontent.com/13745863/90518547-3973e880-e167-11ea-8ab4-ae437d8cb921.png)
